environment:
  op_build_user: "RobotDotNetCI"
  op_build_user_email: "robotdotnet@gmail.com"
  access_token:
    secure: fwCTagTAptB4QJnTt9RrLEvg3G0cEJxssYNxtYFMBKnqHqbGomBTZvvGjrHtt7l4

version: '{branch}-{build}'
image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
branches:  		
  only:		
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: >-
    ./runBuild.ps1

after_build:
- ps: >-
    If (($env:APPVEYOR_REPO_BRANCH -eq "master") -and (!$env:APPVEYOR_PULL_REQUEST_NUMBER)) {

      ./pushToWebsite.ps1

    }
