version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
branches:  		
  only:		
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: >-
    ./runBuild.ps1

    if($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode )  }
